---
name: Compiler
on:
  push: null
jobs:
  windows:
    name: Windows Release
    runs-on: windows-2019
    steps:
    
      - name: Clone Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
        
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          
      - name: Compile auto-mcs
        shell: pwsh
        run: |
          powershell -noprofile -executionpolicy bypass -file .\build-tools\build-windows.ps1

      - name: Upload Executable
        uses: actions/upload-artifact@v3
        with:
          name: auto-mcs-windows
          path: build-tools/dist/
          retention-days: 5


  linux:
    name: Linux Release
    runs-on: ubuntu-20.04
    steps:
    
      - name: Clone Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          
      - name: Install Dependencies
        run: |
          sudo apt update -y
          sudo apt install xvfb fluxbox -y
          export DISPLAY=:0.0
          Xvfb :0 -screen 0 1280x720x24 > /dev/null 2>&1 &
          sleep 1
          fluxbox > /dev/null 2>&1 &
          
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          
      - name: Compile auto-mcs
        run: |
          where python3.9
          where python
          where python3
          python3 --version
          python3.9 --version
          python --version
          alias logname="echo runner"
          export DISPLAY=:0.0
          cd build-tools
          chmod +x build-linux.sh
          sudo ./build-linux.sh

      - name: Upload Binary
        uses: actions/upload-artifact@v3
        with:
          name: auto-mcs-linux
          path: build-tools/dist/
          retention-days: 5
